#!/usr/bin/env ocaml

(*
  Each new term in the Fibonacci sequence is generated by adding
  the previous two terms. By starting with 1 and 2, the first 10
  terms will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values
  do not exceed four million, find the sum of the even-valued
  terms.
*)

let prob2 =
  let (sum, a, b) = (ref 0, ref 0, ref 1) in
  while !a <= 4000000 do
    if !a mod 2 == 0 then sum := !sum + !a;
    let (a', b') = (!b, !b + !a) in
    a := a';
    b := b'
  done; !sum;;

(* 4613732 *)
print_int prob2;;
